"""Publish the reviewed display relations without modifying administrative data."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'data/jin-fief-research/reviewed-kingdom-display-20261004.json'
data = json.loads(source.read_text())
ids = [record['id'] for record in data['records']]
assert len(ids) == len(set(ids))
for record in data['records']:
    assert record['begin'] <= record['end']
    assert record['primary_ids']
    for member in record['members']:
        assert member['certainty'] in ('confirmed', 'inferred')
        assert member['ids']
(ROOT / 'data/jin-multi-kingdoms.js').write_text(
    '// Generated by scripts/build-jin-kingdom-display.py.\nwindow.JIN_MULTI_KINGDOMS = '
    + json.dumps(data, ensure_ascii=False, indent=2) + ';\n')
print(f'Published {len(ids)} reviewed kingdom display periods.')
